apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Define namespace if needed, or rely on Flux targetNamespace
namespace: monitoring
resources:
  - grafana.yaml
  - prometheus.yaml
  - grafana-service.yaml