apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-operator-values
  namespace: monitoring
data:
  values.yaml: |
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: standard
              resources:
                requests:
                  storage: 50Gi
    
    grafana:
      adminPassword: "admin"  # Override in production!
      persistence:
        enabled: true
        storageClassName: standard
        size: 10Gi
    
    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: standard
              resources:
                requests:
                  storage: 10Gi