---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kafka-credentials
  namespace: kafka
spec:
  encryptedData:
    password: AgDjz+5bwHvJprxrnBv3Q0ZKb4ImEjl20eKhhFt48FtXLX/4iP9uq4qwv8INWp9xPoeTSAMaMFdUKOVmCX5dKvLUfnCgki+wf0JFEVQJZGE949wqV/yvgF2Sqtt+GaChlgLCjK4PVfcpWGxNz12qpHfhExt9xu7i8Kkw/BRfQFgA50Sg3Ge18XAZCIxOsxPzf58f/sD+zauo7ZeOJrEaFIoYJj00kW0acUUnEeWJdAfbrNQR2bl9p2egjb/RsAcYBirmf4sYhgqiKmbNf+z3XXUQR1NLzrXibseVYpcBz19T46pVP0Kolbsl4uvQxPPvSHHzi6feRN2EfwnzfAAZGwRhT945uJxaFnSJODI6Ds96qHFWRT5q1HNSJ93NUgrgmGWIb7AYxN04x/lQ3vskMh53iwWotbY7ZFYVurJvrQWPWHktKKC1c4NxVVIm4ETs34I2gdEAw5khtaXb154BEAOPZevTvGkaUuInIrqkuTvlxd3Lr+VFbBREFg7qQ5g42M/epKljsP/Sx/tlUKu7jotAx62KrS54XiYGh6ckPONYTSKsSdtevVqsVAF4LwiWmFrYgZGgoqgSThaLu9ooDC9a7iF79Bjvprv+y+vbTCyrmJARrb3eY0CdJMOtf2rH2EgndkSv6GSjooGRcdlPcBfi0URYOnYw0Zjmz4+Mg/P06VaoDU2u7Mjkmx/BtRNcjfnb0pADzCff
  template:
    metadata:
      creationTimestamp: null
      name: kafka-credentials
      namespace: kafka
    type: Opaque
