apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 15m
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    timeout: 10m0s
  upgrade:
    timeout: 10m0s
  values:
    # Single binary mode for simplicity
    deploymentMode: SingleBinary
    
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: index_
              period: 24h
    
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        storageClass: local-path
        size: 50Gi
    
    # Disable other components for single binary mode
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    
    # Gateway for ingress
    gateway:
      enabled: true
      replicas: 1
    
    # Monitoring
    monitoring:
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
      lokiCanary:
        enabled: false
    
    # Test disabled
    test:
      enabled: false

