apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: loki
spec:
  interval: 15m
  chart:
    spec:
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    timeout: 10m0s
  values:
    config:
      clients:
        - url: http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push
      snippets:
        pipelineStages:
          - cri: {}
    
    # Collect logs from all namespaces
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack

