apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: airflow
  namespace: flux-system
spec:
  interval: 5m
  path: "./apps/airflow"  # Points to central HelmReleases
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-lakehouse

