apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: airflow-helmrelease
  namespace: flux-system
spec:
  interval: 5m
  path: ./flux-config
  prune: false
  sourceRef:
    kind: GitRepository
    name: infra-lakehouse
  dependsOn:
    - name: airflow
      namespace: flux-system
  targetNamespace: airflow
  wait: true
  timeout: 5m
  patches:
    - target:
        kind: HelmRelease
        name: airflow
      patch: |-
        - op: replace
          path: /metadata/namespace
          value: airflow