apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana # New name
  namespace: flux-system
spec:
  interval: 1m # Can be longer than app
  path: "./apps/monitoring/grafana" # Same path
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-lakehouse