apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helmreleases
  namespace: flux-system
spec:
  interval: 5m
  path: "./infrastructure/helmreleases"
  prune: false
  sourceRef:
    kind: GitRepository
    name: infra-lakehouse
  wait: true
  timeout: 5m