apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kustomize-controller-hr-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kustomize-controller-hr-reader
subjects:
- kind: ServiceAccount
  name: kustomize-controller
  namespace: flux-system