apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 10m
  path: "./infrastructure/load-balancer/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-lakehouse
  targetNamespace: metallb-system