# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: minio
#   namespace: flux-system
# spec:
#   interval: 1m
#   path: "./apps/minio"
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: infra-lakehouse
#   targetNamespace: minio  # Deploys MinIO to isolated ns