# flux-config/monitor-kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 1m
  path: "./infrastructure/monitoring"
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-lakehouse
  patches:
    - target:
        kind: HelmRelease
        name: kube-prometheus-stack
      patch: |
        - op: add
          path: /spec/valuesFrom/0
          value:
            kind: ConfigMap
            name: prometheus-operator-values
            valuesKey: prometheus-values.yaml