apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  dependsOn:             # <-- Add this
    - name: monitoring
      namespace: flux-system 
  interval: 1m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "~58.0"  # Pinned version
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    crds: CreateReplace  # Proper CRD handling
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    cleanupOnFail: true
  valuesFrom:
  - kind: ConfigMap
    name: prometheus-operator-values
    valuesKey: values.yaml