apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus # Renamed
  namespace: flux-system
spec:
  interval: 1m
  path: "./apps/monitoring/prometheus"
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-lakehouse