apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-config
  namespace: flux-system
spec:
  interval: 1m
  path: "./flux-config"  # Points to dir with git-repo.yaml and minio-kustomization.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-lakehouse  # Matches the GitRepository you'll create