apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-lakehouse
  targetNamespace: kube-system