apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 1m
  path: "./apps/storage"
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-lakehouse
  targetNamespace: local-path-storage