apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hello-world
  namespace: flux-system
spec:
  interval: 5m
  path: "./infrastructure/test-infra"
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-lakehouse
  targetNamespace: default