apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: local-path-storage
  name: local-path-config-access
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: local-path-storage
  name: local-path-config-access-binding
subjects:
  - kind: ServiceAccount
    name: local-path-provisioner-service-account
    namespace: local-path-storage
roleRef:
  kind: Role
  name: local-path-config-access
  apiGroup: rbac.authorization.k8s.io