apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lakefs
  namespace: lakefs
spec:
  interval: 15m
  chart:
    spec:
      chart: lakefs
      sourceRef:
        kind: HelmRepository
        name: lakefs
        namespace: flux-system
  install:
    timeout: 10m0s
  upgrade:
    timeout: 10m0s
  values:
    # LakeFS configuration with full database connection
    lakefsConfig: |
      logging:
        level: INFO
      blockstore:
        type: s3
        s3:
          endpoint: http://minio.minio.svc.cluster.local:9000
          force_path_style: true
          discover_bucket_region: false
      database:
        type: postgres
        postgres:
          connection_string: "postgres://lakefs_user:LakeFS17@postgresql.postgres.svc.cluster.local:5432/lakefs_db?sslmode=disable"
      auth:
        encrypt:
          secret_key: "lakefs-secret-key-32-bytes-long!"
    
    # S3 credentials via environment variable
    extraEnvVars:
      - name: AWS_ACCESS_KEY_ID
        value: "minio"
      - name: AWS_SECRET_ACCESS_KEY
        value: "minio123"
    
    # Service configuration - NodePort for external access
    service:
      type: NodePort
      port: 80
      nodePort: 30081
    
    # Ingress disabled - use NodePort instead
    ingress:
      enabled: false
    
    # Resources
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

