apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lakefs
  namespace: lakefs
spec:
  interval: 15m
  chart:
    spec:
      chart: lakefs
      sourceRef:
        kind: HelmRepository
        name: lakefs
        namespace: flux-system
  install:
    timeout: 10m0s
  upgrade:
    timeout: 10m0s
  values:
    # LakeFS configuration
    lakefsConfig: |
      logging:
        level: INFO
      blockstore:
        type: s3
        s3:
          endpoint: http://minio.minio.svc.cluster.local:9000
          force_path_style: true
          discover_bucket_region: false
    
    # Use existing secrets for database and auth
    secrets:
      databaseConnectionString:
        secretName: lakefs-secrets
        secretKey: database_connection_string
      authEncryptSecretKey:
        secretName: lakefs-secrets
        secretKey: auth_encrypt_secret_key
    
    # Service configuration
    service:
      type: ClusterIP
      port: 80
    
    # Ingress
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: lakefs.vanir-proxmox.duckdns.org
          paths:
            - path: /
              pathType: Prefix
    
    # Resources
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

