apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lakefs
  namespace: lakefs
spec:
  interval: 15m
  chart:
    spec:
      chart: lakefs
      sourceRef:
        kind: HelmRepository
        name: lakefs
        namespace: flux-system
  install:
    timeout: 10m0s
  upgrade:
    timeout: 10m0s
  values:
    # LakeFS configuration - database and auth will be set via environment variables
    lakefsConfig: |
      logging:
        level: INFO
      blockstore:
        type: s3
        s3:
          endpoint: http://minio.minio.svc.cluster.local:9000
          force_path_style: true
          discover_bucket_region: false
      database:
        type: postgres
      auth:
        encrypt:
          secret_key: "lakefs-secret-key-32-bytes-long!"
    
    # Database connection via environment variable
    extraEnvVars:
      - name: LAKEFS_DATABASE_POSTGRES_CONNECTION_STRING
        valueFrom:
          secretKeyRef:
            name: lakefs-secrets
            key: database_connection_string
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: lakefs-secrets
            key: access_key_id
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: lakefs-secrets
            key: secret_access_key
    
    # Service configuration
    service:
      type: ClusterIP
      port: 80
    
    # Ingress
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: lakefs.vanir-proxmox.duckdns.org
          paths:
            - path: /
              pathType: Prefix
    
    # Resources
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

