apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - kafka
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka
  endpoints:
    - port: tcp-kafka
      path: /metrics
      interval: 30s

