apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgresql
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - postgres
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql
  endpoints:
    - port: tcp-postgresql
      path: /metrics
      interval: 30s

