apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - redis
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s

