apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgres
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: bitnami-postgresql
    namespace: flux-system
  values:
    auth:
      postgresPassword: my-postgres-password
      username: myuser
      password: myuserpassword
      database: mydatabase
    primary:
      persistence:
        enabled: true
        size: 8Gi