---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: airflow-redis-conn-sealed
  namespace: airflow
spec:
  encryptedData:
    connection: AgBcGtOKhr1jaiBbOLirmPeGk4LsjvV14br4DZl9QI5zLrweQCL1K/pdrqO0ZlGdQRqUsKUfpLnD1SXYIcJUKi/SewWz4dRwaKtTIiRpCEs2yazCkcxMbKDCmam3JC7zkpJpfFwEBeEaYJouNInHmyvBmfW0zMTFQGeJmaJzUmhlep+f6Kbv4YAoLHr6MuftewU/Vyn5Csv5N2N4gV4sqBbF9me6dvZLy2DMLzx6je916ZdhO1HaQ58nSm5J0Dz06r1dzoZ8RdqtGJDrEJ3Pt+BWEIsTSJccwafRQiE5eKxFdPq9esK/eU1r4dkD7itePDco/6Gvv8Rs9FRBZjFeBaJyVJB29TVI9yLJb1Z9XUU76hXNKx28VX0nb9h+Mms6lHSoYsQ/XeTXEdovbTg5tbT3XRBYqCTSo4o5DidbDBlnZz2oMZ0kTIuTGFsc3Bzlx7TvQta9brqXuoy61Svm+Ej9+h2dNh6Iwc1PLFm//QW4wdDkB3RSzaHhLELqT1GCW2xbCnqdgaJZYeQyUS5EKVyqd3G43ynUrqyEFbhpcUfcNQqU0NE/3oK2IUEC9vNDm/x/95PP8ECCiYrf9VQdY2OTO1ZbbnipsULay2O95b9OEUrc19q4DDlFmLiiOadsyZPv/ncsx04LH5Hx72UejWs+FfGdUPx3W0RJedhe9cM7KIc2ODy4IQqrSuD6jDodgnvOO/9l53bM56GUQdAgkR4qTAq7BsR5xnrIMLCv5oTQQjIY1lJiTpg91qn6D+iLTJavYgFmUFChXM9yivkshJ/BBnLzpDM8hds3G1Y75g==
  template:
    metadata:
      creationTimestamp: null
      name: airflow-redis-conn
      namespace: airflow
    type: Opaque
