apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: bitnami-airflow
    namespace: flux-system
  install:
    timeout: 15m0s   # <-- extend install timeout (default is 5m0s)
  upgrade:
    timeout: 15m0s   # <-- extend upgrade timeout
  postRenderers:
    - kustomize:
        images:
          # Replace the non-existent bitnami image with bitnamilegacy
          - name: docker.io/bitnami/airflow
            newName: docker.io/bitnamilegacy/airflow
            newTag: "3.0.5"
  valuesFrom:
    - kind: ConfigMap
      name: airflow-values
      valuesKey: values.yaml
