---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: airflow-admin-credentials
  namespace: airflow
spec:
  encryptedData:
    password: AgCu/+xw7zqSQFRjv9k9A0XesJZHyHhOE+3X67tr7noyrS6LzDYq9DI6PknwVSGULjvFAG+8d7DS7VuumToHb1F573Wixp4DO7yByiRqs43uLGq/RyuIm6AqPsV2zUv7IZB7GDDqcsFMfDGObpUwJIrdtJeRBVZmFQmRLr5B0OSAoWCNzX/OQOK173LrpEsfT2N95dpwgLQ7YLlQhdQrAl4Y0ZgCa6zo+plo+7aVedj1ObrSgbIrSqXdN4U6Q/0+OmTzqg82TQu5UDfOXMsc7R1rVlMbcX+dS4cX6u5KS9RC7U5rQdbVcsWG01dGiqctOvQdcmLaVOGOTpyZow8npez9Od2ptTkmRc+sg0OrgffDKXf12rNOIvg/8r+z+Mtsi69uhYC+nmVpJw75LXP6DuF5LqmTt/WPuWGZf611No7WD1beKZxu8WW3pybnrEoJmegrjL+4I8YWZ5lGvPEfZjp+rhtiQz/C3wNKKtufjz+lOAR0nqyZH3OB4eiE+6QuHnV/+QxM9RVbNajg5D2ZYiDbKHd8c6wCtnQe/MqeKuafuTqCcl+icaOjxVs5Tq2ifd9W+C6HAmzj79pidqyVt2o22b/XwJOWFvCN+/W6QJHBOO2mmmntuJIcFlfBjbvzgfz28JoOOkdzcp6YyLiQRi1vfO/BgpLba2msl6TqRT57uSX2OQLrsjZ6Y1bsCWuhJc99C4HS+MTedRU=
    username: AgCybNKatBXiXvK88JRPvg6TPsxepyeOr6dHUjWFaghJej2+AcC9DQAqgIXrHZOouxZ/4GZAcqAI2w3F/TuJGVg2bXfE9A4u1OY/gSMEegnvMhjxX9bnd/9yXc9dp7iemaVRfHgiOWkkqnevphhjjH59/0jbztfUcSAaXMrwTIU0MJ7bvPo3Urgb7UXK6976nv0TRMwweE2/fWOTH14nZd2B0uwjnbnQMSiroa4gBkgR3qkgGMTbWU8LDPkkwYvPRJic4wXJYnXcEbXCIpYv4kbFVDRk3bl0nrE5MycFOSbcLDCM7Sr6d4rhd35PuWzN3w2X8vl7WOio3m8g8OIgXJg6rJ/gMAAN8JVJpKNWr1rj1pDhwdShrb248fpITWv5NT0J+yIkpI1PybTXdPVpmajCYbXq1B8buXlUmQrUXpCEzEEcOsv6KNdpOEv0VZjqtrG/lQIlY8dHccrKZQYpReth0t69FrJcZyP9zUxIc649F8lI2RFbHRe5Jz7jhy7QA/jCq7aHnacuepxr1UskXMJA2XrbcJ04SPWYLHV6/0A34HKXWNleYhyofnu99sIoIBezmYTaD7ej8TaVPoHECghGxKs6ilDm1prHw+IeNgJpqqIViMD3vd1GCrJKkZhnwfsjKI4WJmi75VCxUmuGu0EvegHnTPTqPuDd9KtN45N7A7Kd0vqhqwTIZBXr7CclaFXqlyydbA==
  template:
    metadata:
      creationTimestamp: null
      name: airflow-admin-credentials
      namespace: airflow
    type: Opaque
