---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: airflow-webserver-secret-key
  namespace: airflow
spec:
  encryptedData:
    webserver-secret-key: AgBmhGAwM3nwZOcAhPB3F54z7bTT3x/6nxfJuddDuL5UPnOcIiSHXsHN8Q7TWhcKIJfyj3Tgy3TXXl4Jtm3CwB349Twn5T77cS3G+wQktR32sXCHmG4a8JXJoJQYdi8IGUlF69TE6c4TXjO/VKxs/I+5x9nd+rudoB6sQLTtmW8yCXkKoDN4nsuQUZR2iphn5xhDhJ0uopaeGW2gc6Nz/8cjhnqsduc7P5HT6pqwgi8nkEGqdl+SJCuZ+5QMLIpWscGSika7alQNuQ9gMmWNbC/mQSG3xPN+d/99k0Vdvn3dkzWgIVKUKu7jc/vkBS+yaF6OzMgnNUGAxqgwiobJgZ9OYWtUbMutsRgWSIc1fN/iJfDnQxLSJZulvAD8yvJRStUFBogC6iTcC+1Dqb7qJWUOtjx9VEKQzYJD19DTRLh4FJ9oo4upDavPSj2JSHGryYcXt3+uDQw54KhsPrzCdqoDmDnlI3K0GWCPRXOdmG0v98PoZZbQIppiAk8MmbjauLEM9jrHjF4Hq19xtwV83KGxEDumCArh6xQnhqsNGCf47cXxKvLoO9sftpQE5UMtwHF6mGV3KM2CcryBVWuPSXfdskNxJmz8Gv7KZk8swyWVCcOIhZOJAkdGTelVTVBtw4ckGOSSPQSKKqS59TglxBU45gasJNrJefgtCUbCrIkkzSZxnupe7ZIq6dhzFAYx4/IJqByTA6dX2oPhkE4NX37zYN+uxa3G2AwlnrEUvOwRzmLL8ahO+38x4n/UyJgkd85oHvEFt2M6sh5qaKO3IT8n
  template:
    metadata:
      creationTimestamp: null
      name: airflow-webserver-secret-key
      namespace: airflow
    type: Opaque
