apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: bitnami-airflow
    namespace: flux-system
  install:
    timeout: 15m0s   # <-- extend install timeout (default is 5m0s)
  upgrade:
    timeout: 15m0s   # <-- extend upgrade timeout
  postRenderers:
    - kustomize:
        images:
          # Replace the non-existent bitnami image with bitnamilegacy
          # Match any tag pattern (e.g., 3.0.5-debian-12-r0) and replace with 3.0.5
          - name: docker.io/bitnami/airflow
            newName: docker.io/bitnamilegacy/airflow
            newTag: "3.0.5"
          # Also match the full image reference pattern used by the chart
          - name: docker.io/bitnami/airflow:3.0.5-debian-12-r0
            newName: docker.io/bitnamilegacy/airflow
            newTag: "3.0.5"
  valuesFrom:
    - kind: ConfigMap
      name: airflow-values
      valuesKey: values.yaml
