apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  interval: 15m
  chart:
    spec:
      chart: airflow
      # Optionally pin to a specific Bitnami chart version, e.g. "20.0.0"
      # version: "20.0.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    timeout: 15m0s   # <-- extend install timeout (default is 5m0s)
  upgrade:
    timeout: 15m0s   # <-- extend upgrade timeout
  valuesFrom:
    - kind: ConfigMap
      name: airflow-values
      valuesKey: values.yaml
