---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: airflow-pg-conn
  namespace: airflow
spec:
  encryptedData:
    connection: AgBEac+xCtwg0BsTFrYsZOiG5wDrJsGiGENFxSSNRMNTLaAqHBFX/brrfniGSD5AGIkhmKu/xkqgFp+I+XSCkjbcvzj22NeK2yzZ4D/RbJRh7O641091tN/NZhlCGaMzihclgZ2IftCcr3fHsSZoeQswXczPuKgLDsvnor0d9Gq8GMQ1m0rvQSiph7g9cAuX0hLb094TIJfLKbIPKgdgh3SdFgaP6zAMCkquW05KecoIn2uhbB2B0s6XKLsXbWkjYaKdYv3aXbFwRmkoBxcf2ChFzvhYOizDI7aAwW2eAExIGffBvGVT8HEh1VGXDAMb/5hSVmZUhtl8r/rUJrLdcXGIOXQ0jQdxD4hYxwkWh8jVIuZjY/w3FhJ0/7phVilgUQhPwjuGcQ8nE3FR/TmhLYp2xB/nHtvIoy5cWA4GRC5MKWCvIQN61G8NDQkz+t9ob5gHWaLOjTfRy0IfvRZxYknZAn05W/l9y6W33WSg8D2ZPVVAYhi8Dz5K/Ko4KE3PTl7GeSG4O7vUMMf81N9gdnsR21I0ufSkYWmDJf9XxcR1EUzGvsb+9SLc6iu27ypzi7yN+qhbPWoiE4ld0fDwPLJYdVt7IAv+b/tZCHBZ/TzujFv2H/osWnkWBcVivQqE9cyTR8VTxE3RExiC89HXyv4hsQq1NKX/JVkvW3G3lW8u6IkH/MjkxLlW5n+qrB1ZqCL89cWoTpzir1i8fbPJg/J4M+bL52+FarsRLutYnTVYgc+jw5wBNSAu0/UsokqUZ0JhaaoRtcIMrgsf6FDCeNCTuIOgMIUzZGGH8iSy4pWuKDk=
  template:
    metadata:
      creationTimestamp: null
      name: airflow-pg-conn
      namespace: airflow
    type: Opaque
