---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: airflow-webserver-secret-key
  namespace: airflow
spec:
  encryptedData:
    webserver-secret-key: AgA0lYdgHouXP7of4QMDc+NFw4+n6+u3UmmWz5gXSXt9HJtP6Nf/F8oSitbe4j5hSpAHBz/vtkyaLhoUptUm8DIqBpVGr5JkaI9kU8YXyhAVxxpQwv4Hvu8tb2AfmXBti8JfQ5CxD48OZqjNGj4YYJ5uX6ihoMkNGj6oaDtTkkeKNNiQYZaTSNP1RT99uyYMS7SNq6K8mdjcp2T58pO+C/tPNrR4Kf5dacw7Xdv0hNHWkxiZNmchJKDCxjm1LIqiqamAoIgN860GQwA1SvpyEwtCJr+UjcGtk7iQ6h1IlhF7rHFbHHK3WmL+dNeq/4O5Kara1nI7zXmW/wsQgQXAloPQ7B9b0Gm7Spt0kJK/ReEcFS3Xq+8UndxBVli6njWxLF1FVdbYP+S7IOEXuiSkIbEPYaNlcLEgfEpjNvZKE3y6ZpQjbgNwXM5rl8I4f+5zdh9jWSJlhjSFWaKeeYQl5gh9c6xtc4qeKIO8m4ozmUbrUkuJwRWszdL0KKjtGvw+bJDG3xwH1AcWByLfxf+226cwOhTguR8jPUF0qNrTEkB+CuNO1HAGnA3m3rmlY+jvTqf+iUJsSKVQspgvNRnjjgH/5biugZQJ3xjaS2iWNMr5CS6Wr+vqU1hWZX/DgkG3uE52491W1dd0sYAUDyckI5N33geW+r4OoBMgNtQwb3svzomML3SfQZpxYDpNNjsClFK5wSA9fi78JI2Pj1LQLFeM7YyoiASb4lfl1D8ITHfuf9RHeASDDmgTylM1JPj0IoavGQ8Vr4UPz9MYNK1ViLGv
  template:
    metadata:
      creationTimestamp: null
      name: airflow-webserver-secret-key
      namespace: airflow
    type: Opaque
