---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: airflow-webserver-secret-key
  namespace: airflow
spec:
  encryptedData:
    webserver-secret-key: AgCeTzR0WXWcZEhwxYx6akjHAO3Xh/M0hwJhVe6xs+b3897d0hg22a9AryTSVRqMzT0U1MmU7Cmts5P1zigDl5lFZDF+OoNRFZ6a5dqafQk4oBdJ+LsYvcXNbTxG7qD0wQnGdTbcA2UkMZPomVWktkSJ7KfMqnG+RgPzudgdiIz0mXlgMCV+tmtnBd1Qy6eBR1u/4y/rwMZQPdZfKPqcFMsVTX8tMHy8SwWCo5QzumI4B2e7ixlla9jLHcxiCZ9Kv5XZZ89DYlQ2IvCSJtumUMmTDjeyiHrL3ubXMe/ds+H2+Mj5TwWMEORrg0cvp4ak2wy3BKCxhr1+aqYSwCu3I0LkErENe88MMpQTZjkXq8h1wlBzvy2aFuaf8PDE679QgdBCBi5EdN2aHMcLqhd1+miht3XWkBTUl6cQ4nI2TibhheV4h8QXHXOFB+sQAue8klvdk8wo7ixcP3Ify9zr/NVh7EeA+QDlhL7EQq6kzl/I3bvNXHn6/X+Gf/wX+cxih/J2Gc550f0LQJNYKRVW8qkYMqAYKA5CUJ/98Rv3LWoRxF2TRlxdsW1bKGvQ4vinETIR9lahffH5vM7Qu2r2J+GFmAYRQfO1+Befqqx0eY3R/Eq+jkvLIZvVaETOwac/qkH3jo7xoXXo+SjUld8sTPLCtY8tmgvJwzStzzNKdQVNc4LChyYLiiBcvCFqYMmFUSuk4AHsLCWL2B+yO7S6PY3ob47/8IuVgzSsalJgn2Z3gAKw4x2tIkCdsfAp1MyWqoFxli/OiSEqLlev3NZhL6It
  template:
    metadata:
      creationTimestamp: null
      name: airflow-webserver-secret-key
      namespace: airflow
    type: Opaque
