---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: airflow-redis-conn
  namespace: airflow
spec:
  encryptedData:
    connection: AgBobCNxridQvBV5DJ1HgiZ6H+G/kOgXikpsi9RCsAJHuyuPceGo2j3yejd0H/bDNig34Tb/YduU80UNEmOUXXKAozlOxkeqYrjbuQCgsTzGTn+tnkVkmJpT4kZ0mBYJoshmNb4LYoIte4LrOu/WdqRaK9eOgdYhKna0e73Gus21jeewX12HVAwh6pvKj3Jgfd2S3OdCvc0PTosKM1B5GJeWG6JyFXR5lgqWRKSw50PuZb+OO2PWnquAH3l2VugN8/uXrLrQooyDljRengr1S765Kbgztf8PC/P7QyWybajhUtbnw6zn0sznWut87TF5u1YFKqoDhGLSOcEn2fO/ttmGWbxKSlfTFnEWSEGDivMgovlIrfoqBFFevAScg4Z9qxR3TE1saS+LZ3gT1z6/Y9dgSvTwY5k573tgbo36iHRxeQnY8hB9v8WI6Sd6ssHH5i5QDQyWE+ulmQgihJvnQ+qk1yZwFYvDLx4KxIWkzDtob4CCFMuSqX/KfgK/kD/B9eeLGkqNBu2TXZV/4Sp/QhMCvU8SIQll8QXJo/tjrBhyHyGwt+OS8AHgRt92Td1B+DDSBVESRHWYdgCRfcBbuo+Go/fQ+XfiEkjKF/UAT28GsmeAcD7a6Upj2BGzvIFXWukopfMwEmscGKVBT57dc4n8BIwNgHBYLD3iusVxN5gllK5WWvuK+6Lzjl9wvN5ebUlaEuOcLtJSEQ7ztd98OyWLGqBzcAK44L9rwS8T/WAtm71SG7Ln4fkqC6zPG3cxcF82p5XN4wrbxzJOOD5Dfe/2bcjU2b3KU4au7RuvWUE=
  template:
    metadata:
      creationTimestamp: null
      name: airflow-redis-conn
      namespace: airflow
    type: Opaque
