---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: airflow-admin-credentials
  namespace: airflow
spec:
  encryptedData:
    password: AgCg91vD+qP2bA9JodDoug++vXNKJ7rfvHj/sD0oWx8m0IG9PCLc+GGPjQDSUtFVpLmrKFHnCpkXlLF9BBek5k91FT2hDKYH+VQAjtf/gMHCJsn5tDfJvh0POynscU9rKeFsK3BgHB+ZgHHTqAWRQGLVdf0K09jc0y9Y6vRU6mE8HbiM7r5Ms7s4fmdJCxwFSGOCu7lAxPWjkL8NxHj4UmKbkIC/ocd8CtEjLK5ywuCgk45NJcRQh6n7xcHmMwBHBZnE7XeRskLcXKRJpmI5LRKgAQ037WW0qbUF74Bai7N3vxw4rdUpctSUpqo2R0C7tvC69q3hJFmVIjr3r+Lm10rsbYF7T2I1mriDwSu+N7Dw5dHjG7c3YSG8Cu9SbWm3cRL/nL+prcQOYyX7F/KmF+uWghM9ECsoRX7g58UIWChUipdzwXNlKnOvcA8F0dwHod0a95oCltwX8QYut816S1Ug9OLePZ05zwiwnawDJkPaAZNTTOonaZ/jvjykRPhXRSDW0KDPkShiEmDezezz4y8cw1iL92kGVlXItXs86LTXV1k7bz+SNBpxCgHiUyS0TeFb7vOFqmz1daA8yXU7ymwC6C34nL3QZBFoz4Blp0Ur739upfXosRS/OAmCX90Q8gH56LY45hqS33Jc1l5e52NrcylV/9LOQx2vYQqEtk1aRgwl1D/8I+jCo7u7c+V1LxXmeGPsRWVOFJk=
    username: AgAKy50bfAY8+ZOnu3xpitiKvw92KxQ1siKbMovskVW4pknyna63XgA8Itjm8vI1MKVVmhB1N7PhfVe7eKVO3sT4Ura8/+9QioPvRHdydDONnZbKLTXAhIeHmmxZtsdI2exnLqVl8AnIy9E2SNlsxVBpb9j9Kds+/wmOPsC/+enzhZSc2/rlmuaKou/ZLoMk7fM6L39EUEJ1OAoNrOZdMg1zbhT5sgbn6U5/vxTArov2F3xA7Y1yo2GaaidRTVOxlbeuq+YbDRRJQPTzILtJ5Wn/kLmDwPCRhCBVFRK86pn1jZKMifW8IIVAPm71MC7HzFTQ4hr6o+eWvFz6uuxBSHM/xMmhJQA62YBqGok1S3D3TfaXJ0i+DPIZdcGtV0EiNCl8ycrC5sWVhby/vA5lg/qKcxr82BhxkKTAQEN7eyjipJqe75aJ5MMpV7YtGknnmHgPfrMBQuLnq22LlFPw99xUFvaI7UsHv1iYqmiokYpHR/d02UegOMjNfvJ5ynv4LxkP1gLpj2REv1i6gSuWKTUmIlNgOvcirZsUlH7CUX+ncFXbMVtazKjExknqB8xPUOjNrKqV2lAnWcix7IUkyKkCJahsCTfLdP47PJ7mSBCypnVoPXQy60JMOl/9VeUTHfTqEN4C8Kuu6ENuPe8Bj4NqtXIQUzyMpJTvvwZXSrbTyyVMj662H1k0du8uFbOCmV3IfNm/yg==
  template:
    metadata:
      creationTimestamp: null
      name: airflow-admin-credentials
      namespace: airflow
    type: Opaque
