---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: airflow-webserver-secret-key
  namespace: airflow
spec:
  encryptedData:
    webserver-secret-key: AgCBT0449RGxG9Ici3f/f0PhsycyXfWsLX4EnB/2sM5Aeo48UBKe26YYJEeel0L7YgdD2+0O9YqxxsiUCzvC6YV3wolMeZEf6hbBy9Sfx/IhY1pz+WZKGkh3Dotr7Byi8Iqv/b4FNyy9YENi8Kp8uPFZVZzqdGe9E/OQunviRyRIfV9Vd7Vq0YVZ8teQYk/kFLDxMSNQZ0B8o401FFnjI2qBo+f2qQygNNUvUyl0vKdeEetzw470YRL2Gi43fAADqKngKOBaEfOWRnhIWM/17nLa9mdobbiChhLJGd4OanOcEV7Du7lBODD2f0sv3A4RTe6phCjVGP2tusQ1My5B5e52lKIvLO0iD15s131lTRNJO7M/FVBlVbl8qdWcPN0FXBdNYkJI85OsQUhUBKY82UJP7cxEnc0yWeubE97IdkXkg4/Qh7Vrpdsf8YaesYP36UHLwqkLUMRo6c/gx0HN4xYHrWCwqbhQ1WIYvjeuVDsB8MEgalRCCXt3KHK1vsxKxmzCaMW47Gr9peICULI8WXmZPF7F0eIhgJNMBCbf/QqHmEHtsQHTh3VtupRz05BsUyNPt2rdyxb4JmhnGgRr/2NUtiMssWGlK6KFm65zQNuK5MQ2B9rdRYTdgV1bPANxbtR1S2KQeEduSM9WLWexFFwFHFnlyPssM/1beGRRgK7gmkM18gRHoA9K4Wsgo3FGDVfeVu+P9VesGkXAIA8ryghCxQWK38GexY58JaQQuCgyjx9UfCIe7Dzkk5OHT8yd0JCrPrtiQ6wkVOMraJTJgw6C
  template:
    metadata:
      creationTimestamp: null
      name: airflow-webserver-secret-key
      namespace: airflow
    type: Opaque
