---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: airflow-pg-conn-secret
  namespace: airflow
spec:
  encryptedData:
    connection: AgBjxgVp1XaS+GkTFqNlcKfKt+FaaSJ13Z2azpL78avZfCcGjccyEWUzTcELNqcp7QS20X9+vI0jjEmNfhv9tdZDMxOjtV5+llLN9Yg0bDRHIMZrfto4FN/SnLRg3U18XVOn2td7OV350jy5hsicSq27AA1YpWQ/BaQq07QMqP/7hfr7E3qwmwPlrfIrNpGLeL5lIUIqXHX6Z5oGdpqXMOcghQapxiWLxORF7IusVe3f7ZF8Dz2ALyTIYTbGlBrVT6mA9ge2Rg2Ii6L69RCp33rn3SJhTlxQshI/lO5EjEQ92sbrb0a2Shmo8PX0Omok944nrd9ZYKd90ADMDkQ9BSnCFdcUBN+eU/mt/5eZud20EJT/4Tsam2PRwskkMn7NutUiygR3ywFBytl2fcUfY7051Fc1GLh/jpbBO6uwN+iElyWTDvA3cZKZoHzYDv+EbTLcgFXTmk5+YG+wqmlA/bIrousX/ZWaBUJ3ns/906FEACrAJw4gwd6Xfg/vZeVSkgk/BKy89WWYzjfj6cqQ4yEipaPiiS+/UMLUC31VkgJsK8z6YxLtFxkMq9L4YBYDJZcNhYmo7/lkWgE1X6KzHzSENiGbOhYEAAIM0d79gLbg5FUv0m8uNhVB10kDVIqZs80iT6PNAWNsaL0aF0QfAgqjjUrLsYturz+dnU8ETYgyQ4vkJYVb96ag3Tk/bkqGaKHrAoa5JrkzFgous3hH8QMQ7I8zjRJaXFweg8WVSoACEun5p7MhyNVNUoFfuwM+kx2y4KnSktpuGkjUMW66fjKZ5exASkPLZJ8rBEPdrQa+e/Hk1Xw=
  template:
    metadata:
      creationTimestamp: null
      name: airflow-pg-conn-secret
      namespace: airflow
    type: Opaque
