---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: airflow-webserver-secret-key
  namespace: airflow
spec:
  encryptedData:
    webserver-secret-key: AgCYVTZpneSXistDkSbhRHHRQ9JlXX7jWMyu0+izdTUN+lTE1oVJqzZXk6s9DEb9BeYGv3n+NbYBNHQlkVFFOIXDqLTs3Rlqi/sVgTdPk3hto0pJKmKxw5nXwUami4uKhR3lRFbOsol8SQV7Scb2QGq9qFk4fH/H6u20B5MmNH9oOSEoAYiLibEzi2Jr/ghSbvHNiab8yeN7k/cgdSc0TSdWX4TlNn2Mk9MCYD6XhqUxUbrWrZQTxZwdxwftLYabqgzhC6ge9WpnmrrGXdDyAKPq/l7bUHGVea5I4ZjElUiN514f/vxly0Rd9TuKBCP8qLZgscFPRM8RXJFfEh5GNvU1kjr0ROFqkt/VuNNa5kRJ7pmNG3AAwwmwYC8G0vevN8ZrWw0j/pioNfIY665kuuH0uqE+JpKaYfNhHWjyM1NEe5Z2dheaVHFvpWGzfl3cz6x5vXmtoATxT82aFYps+zsIF6uAlDpP+Z1CA918WApR+rXLZQL0c+3HV62kSIf1LA9yH/+x2sZIbeFT5j73eOK6d24pGXmHeNAqnYmjyBXgay1ntOpMCc4Fv26tgjd5zMl7qa7aYmpMK8KQKCX87iuJGSc+fAQ/yXk1kPygIcKja+QQWAHxLmmbMEkyOzJMDcFWprhXGU0OG/gvCCeuVHxhOuIYjVmwjAfpYlLvaNt3eBUHyoYme+2K7rz5tU9nniMY9+J72TWE7P+NhFdKO0rYk/uUggZYNHbTQdVHm0ZLysRAMoLZLtYxM2026TyOcvt46B0CUhxAcQVD1gD9Q77A
  template:
    metadata:
      creationTimestamp: null
      name: airflow-webserver-secret-key
      namespace: airflow
    type: Opaque
