apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  interval: 5m
  install:
    timeout: 30m0s
  upgrade:
    timeout: 30m0s
  chart:
    spec:
      chart: elasticsearch
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      # Use latest version - omit version to get latest
  values:
    # Single node setup - disable cluster.initial_master_nodes
    replicas: 1
    
    # Disable cluster bootstrapping for single-node mode
    clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
    
    # Persistent storage
    volumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 100Gi
    
    # Security settings - single-node mode configured here
    esConfig:
      elasticsearch.yml: |
        xpack.security.enabled: true
        xpack.security.transport.ssl.enabled: true
        xpack.security.http.ssl.enabled: false
        discovery.type: single-node
    
    # Disable master node bootstrapping (conflicts with single-node)
    clusterInitialMasterNodes: ""
    
    # Extra environment variables
    extraEnvs:
      - name: ELASTIC_PASSWORD
        valueFrom:
          secretKeyRef:
            name: elasticsearch-master-credentials
            key: password
    
    # Resources
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"

