---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: elasticsearch-credentials
  namespace: elasticsearch
spec:
  encryptedData:
    password: AgAwF4d2wHzj+8L25RuTdKsquHOCduUt0Np0hjkp0fjUrKa5xVpNPg3mHfEgga9QRtNGLn2kwuQROxkhbNGP5mYRTxy6O+pKfN2laqo/R+L7hhpKSfsmMhMH3EQgHLusJ12PDwERPYE4nSzEegSsZNrUArZ3z+NIG8AuPb7mnjK9fLDLC6ysxgg8Abj4FBxxdsasB9WnxAmbxd1+iSbUT0Go9ydTBuj1HEw+j0BqclDKTyeBU8XH49o6poL8/q8hl1gkXgX5+fUYrFk8PtkzthFvRE2b4zzjpPgg94xdXOnPNjFSUhVRooJECMQVEARJLPDxDG1fFUYNPdo+3qnQQS9olJHmkswXMaWbM+3zRTlOiYb3EyC/2xP61QcANZw11YxB5vVm8X9gWE4JKikXB0/QZoDgK9vstjcWu4MtgbF7Ve0eATUhZFRLkA+Optp2ldQ4RYg9tRxfOVMmF5Hbxwx88NKlieQeb+eHoKM54TOmFVUnfD6xOiVworINYY/IfxuLCWCA4h8/wnmFvYz6fU1BhPaSRFXP6NgR34r5HeM/YGDJi5FDP7uKCwd6LQBg/Qje3D/KpP1QpB+WUuW6VXKSOsfhmo1iQtO5W3KkeanrW818a0cBsY1XfzBWS7IAbAEqFLvgRIBNxrGCqBVT68kn4cAmZBYvrNSOPtZg0FNHj/BrbkfnlwEDsB8HucQ5rThxVlTRTqW84PXDG3IY4Ss=
  template:
    metadata:
      creationTimestamp: null
      name: elasticsearch-credentials
      namespace: elasticsearch
    type: Opaque
