apiVersion: v1
kind: Service
metadata:
  name: postgresql-lb
  namespace: postgres
spec:
  type: LoadBalancer
  loadBalancerIP: "192.168.32.75"
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/name: postgresql