# infrastructure/minio/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: minio
spec:
  serviceName: minio
  replicas: 4  # 4 pods = 4 PVCs
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        args:
        - server
        - http://minio-{0...3}.minio.minio.svc.cluster.local/data  # Distributed mode DNS
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-secrets
              key: root-user
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-secrets
              key: root-password
        volumeMounts:
        - name: storage
          mountPath: /data
  volumeClaimTemplates:  # Critical: Auto-creates PVCs per pod
  - metadata:
      name: storage
    spec:
      accessModes: [ReadWriteOnce]  # Minikube only supports RWO
      resources:
        requests:
          storage: 1Gi  # Size per pod