apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-console-ingress # Keeping the existing name
  namespace: minio
  annotations:
    # This rewrite-target is for the /console(/|$)(.*) path.
    # $2 captures the part after /console/ (e.g., "static/main.js" or an empty string if just /console or /console/)
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - host: minio.ui.vanir-proxmox.duckdns.org
    http:
      paths:
      - path: /console(/|$)(.*) # Matches /console, /console/, /console/path
        pathType: ImplementationSpecific # Required for regex in path
        backend:
          service:
            name: minio-ingress # Or your actual MinIO K8s Service name for the console
            port:
              number: 9001  