apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: minio
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    # CRITICAL: Ensure there is NO rewrite-target annotation here that
    # would strip the /console prefix for the /console path rule below.
    # If you have something like:
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
    # or any other rewrite rule that affects the /console path by stripping
    # its prefix, REMOVE IT or COMMENT IT OUT for this Ingress resource.
spec:
  ingressClassName: nginx
  rules:
  - host: minio.teste.local
    http:
      paths:
      - path: /console/ # For MinIO Console
        pathType: Prefix # With no rewrite, this should pass /console/... as is
        backend:
          service:
            name: minio-ingress # Or 'minio', matching your service name
            port:
              number: 9001
      - path: / # For MinIO API
        pathType: Prefix
        backend:
          service:
            name: minio-ingress # Or 'minio', matching your service name
            port:
              number: 9000