apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: minio
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1  # Strip "/minio" prefix
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
spec:
  ingressClassName: nginx
  rules:
  - host: minio.teste.local
    http:
      paths:
      - path: /console/?(.*)  # Capture paths after "/minio/"
        pathType: ImplementationSpecific
        backend:
          service:
            name: minio-ingress  # Matches the Service name
            port:
              number: 9001   # Console port
      - path: /api # Route the root path (and everything under it not matched by /console)
        pathType: Prefix # Use Prefix for standard API access
        # NO rewrite-target should be needed here for the API
        # unless your MinIO API is served from a subpath internally, which is not standard.
        backend:
          service:
            name: minio-ingress # Your MinIO service name
            port:
              number: 9000   # MinIO API port