apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: minio
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    # No forbidden snippets - using standard headers
    nginx.ingress.kubernetes.io/proxy-set-header: "Host $host"
    nginx.ingress.kubernetes.io/proxy-set-header: "X-Real-IP $remote_addr"
    nginx.ingress.kubernetes.io/proxy-set-header: "X-Forwarded-Proto $scheme"
spec:
  ingressClassName: nginx
  rules:
  - host: minio.vanir-proxmox.duckdns.org
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: minio
            port: 
              number: 9000  # API/S3 endpoint
      - path: /console(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: minio
            port: 
              number: 9001  # Web console