---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secrets
  namespace: minio
spec:
  encryptedData:
    root-password: AgBmhkbhIcd4Lv5SB7YeyoDe8fuJL/KqXmT8dIJyt5DIOtIAUOYuHhaVgryzuZwFcR4w2YmbOsYH6dP1MgyhYiJ02fq3HAOs+kucIw3O3fGNqVZlSHsnyW0PU3eSx24fWmPIvWELoKeiPf5FsRE6h82Po+nBEkYWu+GI6G0KB4rfGO6cCtmuKP0lUVeevcMNZGNEjoozY437JWuXKF8jCL4536812/3FrUMEDlKSQOcmd9FkNbUE70ecN8GPLogOWVDKjUbILvWCRqXqaD5OtxkocP1u07rUKq2Ve3Ausaku9rgQl2Kd+xd8lfuEfhQ1Fd6v41t7QT9wpy1DDJcHYH7JRdYUss9fZUGl5Km5ALW0IrWOg4+g9xttd+d1E/INmWndQa8T94B4newp3WI6512o8ZS0ug7dE7bXJRPyj1CiK0ctsV9cQSWkaZXRTW8Q/7X71IWRxbphuVbOLJrgv987elGDdsNvqz8OLrEorvVEke9TovopExh1yZU5yDPf9D+bGSfXAGme0a+ynopluTRnBtpFNk6rk8lFtYBgaOtNxHIzWmBC7lAh6h+UgMo87FkqRko/h7j0VS7yBR+sBMAyReVUU5Lgmqn85w2NylHfQz7opeBqECYUZ2uhTUDSG+oJH37rWFFXE/uPKAgpT5VXRjZBsJM+sbnJzAlO1aJrFiIWx4gcqFpEQlhPrbsfRr/NxiX/qmlEgVU=
    root-user: AgBGIgln6yCvhoPRBXzco6HPrlUPG9RhXA0G2x7cI5CNO+iMCZVBPNOn5Y2g+X8QTfuhwVMTzGp1TsHvyWrUl+oqBRA73mVPOs11uyIaZp+1fZGEJ9LQ10XQjrF8DyEUhYHwQpW1DbYunIur90bcTqiGqZEPBuCWJ8lwW/+fEI0GyWjIukI8vbRHlO39vGDmurBh2bwMrXEgn0rLtCJARmutthlCi9y+SehTTQ7gOdeUo7gZ1Q3AalV+A8Q2TZ8fBz+wLRTqRdryhytUn8pT3lj4+NfY6HcI1Oph/8lRGE1DGbzHSniZR7UzjyOpj2d2tJ1cuZECFcNzR8uAt9gBetr3/YIFoGq72Se9MIF8BKV0zF5PdaUCJJ4O+GhMr8rQBYk02Zd66zhDrcpri9AMFjKXQxnkqT8oCzGWDsA7PP7hJGcL4cFxkkMAyxEcvlBxe6E4AWDL5M6oabhiiZIHgqhYUEHM06RNMIm43CBsOtgByG3MFEiCksHXBRv5Tyu20JHYh6AucXJo9LZonOYQL2w2BdYHHZ4oIVmBAzsrGZhqsKLhcGVkSR1FEutS8x70+mdbBm6fOEFyYmXDZDZMyU25KJdVN1kzZKVxquq9sXrSkL5aBj5jMNLy9IpdNFqniKEpL2u1GrDm+rmv8SLvAxfYt03Tf0sOFAnfZanWaAsKpwNdnJD4DsDkhwhzxosRQxpA5m5C6Dfu
  template:
    metadata:
      creationTimestamp: null
      name: minio-secrets
      namespace: minio
    type: Opaque
