apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: minio
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi  # Adjust size
  storageClassName: local-path # Use `kubectl get storageclass` to verify