# infrastructure/minio/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: minio
type: Opaque
data:
  root-user: YWRtaW4=          # admin (base64-encoded)
  root-password: c3VwZXItc2VjcmV0  # super-secret (base64)