
apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: minio
type: Opaque
data:
  root-user: Um9kcmlnbw==          # admin (base64-encoded)
  root-password: TGF6YXJ1czE3 # super-secret (base64)