# clusters/my-cluster/infrastructure/minio/minio-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: minio
spec:
  serviceName: minio
  replicas: 4
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        args:
        - server
        - http://minio-0.minio.minio.svc.cluster.local/data
        - http://minio-1.minio.minio.svc.cluster.local/data
        - http://minio-2.minio.minio.svc.cluster.local/data
        - http://minio-3.minio.minio.svc.cluster.local/data
        - --console-address
        - :9001
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-secrets
              key: root-user
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-secrets
              key: root-password
        - name: MINIO_BROWSER_REDIRECT_URL
          value: "https://minio-ui.vanir-proxmox.duckdns.org/console/"
        ports:
        - containerPort: 9000
          name: minio
        - containerPort: 9001
          name: console
        volumeMounts:
        - name: data
          mountPath: /data
        readinessProbe:
          httpGet:
            path: /minio/health/ready  # Subpath-aware health check
            port: 9000
          initialDelaySeconds: 10     # Delay first probe to allow MinIO to start
          periodSeconds: 15           # How often to probe
          timeoutSeconds: 5           # When to time out the probe
          failureThreshold: 3         # How many failures before marking as Unready
          successThreshold: 1  
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 30     # Delay first probe
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-path"
      resources:
        requests:
          storage: 10Gi