apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  interval: 5m
  chart:
    spec:
      chart: airflow
      version: "1.13.0" # Use the latest stable version or pin as needed
      sourceRef:
        kind: HelmRepository
        name: apache-airflow
        namespace: flux-system
  values:
    executor: "CeleryExecutor"
    airflow:
      image:
        repository: apache/airflow
        tag: "2.9.1"
      fernetKey: "REPLACE_ME_WITH_A_SECURE_KEY"
      secretKey: "REPLACE_ME_WITH_A_SECURE_KEY"
    web:
      defaultUser:
        enabled: true
        username: admin
        password: admin
    redis:
      enabled: true
    postgresql:
      enabled: true
    flower:
      enabled: true
    ingress:
      enabled: false