apiVersion: v1
kind: Service
metadata:
  name: redis-lb
  namespace: redis
spec:
  type: LoadBalancer
  loadBalancerIP: "192.168.32.72"
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app.kubernetes.io/name: redis