---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
spec:
  encryptedData:
    secretkey: AgBYaq68sMV1s87Iob5uRzh8NvrCFGtvqzRFWvVwb/YGcE3MzOZ7g5ZVl3Y2VKs8kcjmUXWGKDwGSGEF/YsKbqwBE+SvsKJmRTozGDojk7x28HOm4T7uMNRsLxz8lLsvzvKHtxdgBq4nEgU3XCJDPWMo5PVj2+7cdBiupxYglKka6RoTyd99E8svQe+S6p1amlfnXf/8X7ifP+j1BaMXOT/RRu5sfL4lJeToCctjGiltAYJFnZjAvXThJXuXPFbORbkTlpceLH9tuNQ5eCQ+9FYZAR5bCnsaijs1fnH2mfW5AfSxT9OALTtPcPH7t6ZJZdif0JmpiSt3qp2bF8lvrLisvu2M0iDYX3u04RZ5Mfpi/n5ad90YlpMXhW3Ur8lwwUZVIhRZonlFoLP8pbzDZFE14BnnzlXKWUtDM7vEmHDYgHtr1bkKv1RhRlb5ItjixLnGScQHMTOujjfuBLozimDaNfiXTcr2Iccv7tLvcHx1K87iPrHlKafeh88YRc1mUEfY5u5S9L8oDZuRA0sUnB/2EJS/zkA9Zl3lubQXRk5pEUjOPT1yJYWJ9FqLmvLVDFAyXaXF6jcPE8UUxM0HHuu5GjCDuiNV7movYouzAUG5qg6Qa+TaG7qpotqPTplSe5EkQjuF7jTHJejm+/r3V7uwUKXSvK01tPmZIyTxDSEj6cr8Xgipgp5VddRZxaM3GFnpcrt0/9VM9Gkd6eZ7OtrFMufzScaAoOSFvJJnRSEn/Zgf/XX21zClFFKQ3KcbJRbUJargeqM1dSn4YZ3zMVwRb3pUfrH7vvMSq8qxg3HK4BUb0d7ATvix0bxsfBSfdTIjhrhAXWsaO4YadlXqEmWzwxV0Gp95vJiiIHOcn/7EGBBLJG8eFv5+hbhXs1gzB5Xd+H+OOUeqJjY7oAJ3ywlYc/c++ICOgPjjc4US
  template:
    metadata:
      creationTimestamp: null
      name: memberlist
      namespace: metallb-system
    type: Opaque
